-- Database: EXCHCORECPA400 Metadata version: 1 Exported: 19-Feb-2025
-- Begin Tables
SET LEGACYTYPESALLOWED = ON;
-- Begin Multi-Line Statement
SET TRUENULLCREATE = OFF;CREATE TABLE "Stock" USING 'Stock\Stock.dat' DCOMPRESS PAGESIZE=2048 LINKDUP=4 (
 "stStockCode" LSTRING(21),
 "stIdxStockCode" CHAR(20),
 "IdxStockCode" CHAR(16) /* Column Stock.IdxStockCode has the same offset as another column that is not type BIT */,
 "stDesc1" LSTRING(36),
 "stIdxDesc1" CHAR(35),
 "stDesc2" LSTRING(36),
 "stDesc3" LSTRING(36),
 "stDesc4" LSTRING(36),
 "stDesc5" LSTRING(36),
 "stDesc6" LSTRING(36),
 "stAltCode" LSTRING(21),
 "stIdxAltCode" CHAR(20),
 "stSuppTemp" LSTRING(11),
 "stIdxSuppTemp" CHAR(6),
 "stSalesGL" INTEGER,
 "stCOSGL" INTEGER,
 "stP&LGL" INTEGER,
 "stBalSheetGL" INTEGER,
 "stWIPGL" INTEGER,
 "stReOrderFlag" LOGICAL,
 "stMinFlag" LOGICAL,
 "idxStockFolio" INTEGER,
 "stStockFolio" INTEGER /* Column Stock.stStockFolio has the same offset as another column that is not type BIT */,
 "stIdxStockCat" CHAR(20),
 "stStockCat" CHAR(16) /* Column Stock.stStockCat has the same offset as another column that is not type BIT */,
 "stStockType" CHAR(1),
 "stUnitOfStock" LSTRING(11),
 "stUnitOfSale" LSTRING(11),
 "stUnitOfPurch" LSTRING(11),
 "stCostPriceCur" UTINYINT,
 "stCostPrice_1" SMALLINT,
 "stCostPrice_2" INTEGER,
 "stSalesBandACur" UTINYINT,
 "stSalesBandAPrice_1" SMALLINT,
 "stSalesBandAPrice_2" INTEGER,
 "stSalesBandBCur" UTINYINT,
 "stSalesBandBPrice_1" SMALLINT,
 "stSalesBandBPrice_2" INTEGER,
 "stSalesBandCCur" UTINYINT,
 "stSalesBandCPrice_1" SMALLINT,
 "stSalesBandCPrice_2" INTEGER,
 "stSalesBandDCur" UTINYINT,
 "stSalesBandDPrice_1" SMALLINT,
 "stSalesBandDPrice_2" INTEGER,
 "stSalesBandECur" UTINYINT,
 "stSalesBandEPrice_1" SMALLINT,
 "stSalesBandEPrice_2" INTEGER,
 "stSalesBandFCur" UTINYINT,
 "stSalesBandFPrice_1" SMALLINT,
 "stSalesBandFPrice_2" INTEGER,
 "stSalesBandGCur" UTINYINT,
 "stSalesBandGPrice_1" SMALLINT,
 "stSalesBandGPrice_2" INTEGER,
 "stSalesBandHCur" UTINYINT,
 "stSalesBandHPrice_1" SMALLINT,
 "stSalesBandHPrice_2" INTEGER,
 "stSalesUnits_1" SMALLINT,
 "stSalesUnits_2" INTEGER,
 "stPurchUnits_1" SMALLINT,
 "stPurchUnits_2" INTEGER,
 "stVATCode" CHAR(1),
 "stDepartment" CHAR(3),
 "stCostCentre" CHAR(3),
 "stQtyInStock_1" SMALLINT,
 "stQtyInStock_2" INTEGER,
 "stQtyPosted_1" SMALLINT,
 "stQtyPosted_2" INTEGER,
 "stQtyAllocated_1" SMALLINT,
 "stQtyAllocated_2" INTEGER,
 "stQtyOnOrder_1" SMALLINT,
 "stQtyOnOrder_2" INTEGER,
 "stQtyMin_1" SMALLINT,
 "stQtyMin_2" INTEGER,
 "stQtyMax_1" SMALLINT,
 "stQtyMax_2" INTEGER,
 "stReOrderQty_1" SMALLINT,
 "stReOrderQty_2" INTEGER,
 "stShowAsKit" LOGICAL,
 "stCommodCode" LSTRING(11),
 "stSaleUnWeight_1" SMALLINT,
 "stSaleUnWeight_2" INTEGER,
 "stPurchUnWeight_1" SMALLINT,
 "stPurchUnWeight_2" INTEGER,
 "stSSDUnit" LSTRING(11),
 "stSSDSalesUnit_1" SMALLINT,
 "stSSDSalesUnit_2" INTEGER,
 "stBinLocation" LSTRING(11),
 "stIdxBinLocation" CHAR(10),
 "stStkFlag" LOGICAL,
 "stCovPr" SMALLINT,
 "stCovPrunit" CHAR(1),
 "stCovMinPr" SMALLINT,
 "stCovMinUnit" CHAR(1),
 "IdxSupplier" CHAR(6),
 "stSupplier" CHAR(6) /* Column Stock.stSupplier has the same offset as another column that is not type BIT */,
 "stQtyFreeze" DOUBLE,
 "stCovSold" DOUBLE,
 "stUseCover" LOGICAL,
 "stCovMaxPr" SMALLINT,
 "stCovMaxUnit" CHAR(1),
 "stReOrderCur" UTINYINT,
 "stReOrderPrice" DOUBLE,
 "stRODate" LSTRING(9),
 "stQtyTake" DOUBLE,
 "stStkValType" CHAR(1),
 "stHasSerNo" LOGICAL,
 "stQtyPicked" DOUBLE,
 "stLastUsed" LSTRING(9),
 "stCalcPack" LOGICAL,
 "stJobAnal" CHAR(10),
 "stUser1" LSTRING(21),
 "stUser2" LSTRING(21),
 "stBarCode" LSTRING(21),
 "stIdxBarCode" CHAR(20),
 "stRODepartment" CHAR(3),
 "stROCostCentre" CHAR(3),
 "stLocation" CHAR(3),
 "stPricePack" LOGICAL,
 "stDPackQty" LOGICAL,
 "stKitPrice" LOGICAL,
 "stKitOnPurch" LOGICAL,
 "stDefLineType" UTINYINT,
 "stQtyReturn" DOUBLE,
 "stQtyAllocWOR" DOUBLE,
 "stQtyIssueWOR" DOUBLE,
 "stUseForEbus" UTINYINT,
 "stWebLiveCatalog" LSTRING(21),
 "stWebPrevCatalog" LSTRING(21),
 "stUser3" LSTRING(31),
 "stUser4" LSTRING(31),
 "stValSerialAvgCost" UTINYINT,
 "stSpare1" UTINYINT,
 "stSSDDespatchUplift" DOUBLE,
 "stSSDCountry" LSTRING(6),
 "stTimeChange" LSTRING(7),
 "stInclusiveVATCode" CHAR(1),
 "stSSDArrivalsUplift" DOUBLE,
 "stSpare2" UTINYINT,
 "stOperator" LSTRING(11),
 "stImageFile" LSTRING(31),
 "stTempBinLocation" LSTRING(11),
 "stQtyPickedWOR" DOUBLE,
 "stWOPWIPGL" INTEGER,
 "stWOPAssemblyTime" INTEGER,
 "stWOPROLeadTime" INTEGER,
 "stWOPAutoCalcTime" LOGICAL,
 "stBOMAssemblyTime" INTEGER,
 "stWOPMinEconBuild" DOUBLE,
 "stUsesBins" LOGICAL,
 "stSalesWarrantyLengt" UTINYINT,
 "stManWarrantyLength" UTINYINT,
 "stSalesWarrantyUnits" UTINYINT,
 "stManWarrantyUnits" UTINYINT,
 "stPurchaseReturnQty" DOUBLE,
 "stSalesReturnGL" INTEGER,
 "stRestockCharge" DOUBLE,
 "stSpare3" INTEGER,
 "stSpare4" LOGICAL,
 "stPurchaseReturnGL" INTEGER,
 "stRestockFlag" CHAR(1),
 "stLastStockType" CHAR(1),
 "stUser5" LSTRING(31),
 "stUser6" LSTRING(31),
 "stUser7" LSTRING(31),
 "stUser8" LSTRING(31),
 "stUser9" LSTRING(31),
 "stUser10" LSTRING(31),
 "stIsService" LOGICAL,
 "ExtStockCode" LSTRING(121),
 "stIdxExtStockCode" CHAR(120),
 "ProdImageText" LSTRING(121),
 "stUser11" LSTRING(31),
 "stUser12" LSTRING(31),
 "stUser13" LSTRING(31),
 "stUser14" LSTRING(31),
 "stUser15" LSTRING(31),
 "stUser16" LSTRING(31),
 "stTaricCode" LSTRING(15),
 "stSSDSalesGrossWt_1" SMALLINT,
 "stSSDSalesGrossWt_2" INTEGER,
 "Spare5" CHAR(184) );SET TRUENULLCREATE = ON;
-- End Multi-Line Statement
CREATE INDEX "stAltCodeIdx" USING 6  ON "Stock" ( "stIdxAltCode" );
CREATE INDEX "stBarCodeIdx" USING 8  ON "Stock" ( "stIdxBarCode" );
CREATE INDEX "stBinIdx" USING 7  ON "Stock" ( "stIdxBinLocation" );
CREATE UNIQUE INDEX "stCategoryIdx" USING 2  ON "Stock" ( "stIdxStockCat", "stIdxStockCode" );
CREATE UNIQUE INDEX "stCodeIdx" USING 0  ON "Stock" ( "stIdxStockCode" );
CREATE UNIQUE INDEX "stDescIdx" USING 3  ON "Stock" ( "stIdxDesc1" );
CREATE UNIQUE INDEX "stExtStkCodeIdx" USING 9  ON "Stock" ( "stIdxExtStockCode" );
CREATE UNIQUE INDEX "stFolioIdx" USING 1  ON "Stock" ( "idxStockFolio" );
CREATE UNIQUE INDEX "stMinK" USING 4  ON "Stock" ( "stIdxSuppTemp", "stReOrderCur", "stIdxStockCode" );
CREATE UNIQUE INDEX "stValIdx" USING 5  ON "Stock" ( "stBalSheetGL", "stIdxStockCode" );
SET LEGACYTYPESALLOWED = OFF;
-- End Tables
