-- Database: EXCHCORECPA400 Metadata version: 1 Exported: 19-Feb-2025
-- Begin Tables
SET LEGACYTYPESALLOWED = ON;
-- Begin Multi-Line Statement
SET TRUENULLCREATE = OFF;CREATE TABLE "StockLocation" USING 'STOCK\MLOCSTK.DAT' DCOMPRESS PAGESIZE=2048 LINKDUP=3 (
 "slIdxRecSub" CHAR(2),
 "slSubType_D" CHAR(1),
 "slIdxStockLoc" CHAR(30),
 "slIdxLocStock" CHAR(45),
 "slIdxSupp" CHAR(31),
 "slStockCode" LSTRING(21),
 "idxStockCode" CHAR(20),
 "slStockFolio" INTEGER,
 "slLocCode" LSTRING(4),
 "IdxLocCode" CHAR(3),
 "slQtyInStock" DOUBLE,
 "slQtyOnOrder" DOUBLE,
 "slQtyAllocated" DOUBLE,
 "slQtyPicked" DOUBLE,
 "slQtyMin" DOUBLE,
 "slQtyMax" DOUBLE,
 "slQtyFreeze" DOUBLE,
 "slReOrderQty" DOUBLE,
 "slReOrderDate" LSTRING(9),
 "slRoDepartment" LSTRING(4),
 "slROCostCentre" LSTRING(4),
 "slDepartment" LSTRING(4),
 "slCostCentre" LSTRING(4),
 "slBinLocation" LSTRING(11),
 "slSalesBandACur" UTINYINT,
 "slSalesBandAPrice_1" SMALLINT,
 "slSalesBandAPrice_2" INTEGER,
 "slSalesBandBCur" UTINYINT,
 "slSalesBandBPrice_1" SMALLINT,
 "slSalesBandBPrice_2" INTEGER,
 "slSalesBandCCur" UTINYINT,
 "slSalesBandCPrice_1" SMALLINT,
 "slSalesBandCPrice_2" INTEGER,
 "slSalesBandDCur" UTINYINT,
 "slSalesBandDPrice_1" SMALLINT,
 "slSalesBandDPrice_2" INTEGER,
 "slSalesBandECur" UTINYINT,
 "slSalesBandEPrice_1" SMALLINT,
 "slSalesBandEPrice_2" INTEGER,
 "slSalesBandFCur" UTINYINT,
 "slSalesBandFPrice_1" SMALLINT,
 "slSalesBandFPrice_2" INTEGER,
 "slSalesBandGCur" UTINYINT,
 "slSalesBandGPrice_1" SMALLINT,
 "slSalesBandGPrice_2" INTEGER,
 "slSalesBandHCur" UTINYINT,
 "slSalesBandHPrice_1" SMALLINT,
 "slSalesBandHPrice_2" INTEGER,
 "slReOrderPrice" DOUBLE,
 "slReOrderCur" UTINYINT,
 "slCostPrice" DOUBLE,
 "slCostPriceCur" UTINYINT,
 "slSalesGL" INTEGER,
 "slCOSGL" INTEGER,
 "slP&LGL" INTEGER,
 "slBalSheetGL" INTEGER,
 "slWIPGL" INTEGER,
 "slStkFlag" LOGICAL,
 "slMinFlag" LOGICAL,
 "slTempSupp" LSTRING(7),
 "slSupplier" LSTRING(7),
 "slLastUsed" LSTRING(9),
 "slQtyPosted" DOUBLE,
 "slQtyTake" DOUBLE,
 "slROFlag" LOGICAL,
 "slTimeChange" LSTRING(7),
 "slQtyAllocWOR" DOUBLE,
 "slQtyIssuedWOR" DOUBLE,
 "slQtyPickedWOR" DOUBLE,
 "slWOPIssuedWIPGL" INTEGER,
 "slSalesWarrantyLengt" UTINYINT,
 "slSalesWarrantyUnits" UTINYINT,
 "slManWarrantyLength" UTINYINT,
 "slManWarrantyUnits" UTINYINT,
 "slPurchaseReturnQty" DOUBLE,
 "slSalesReturnGL" INTEGER,
 "slRestockCharge" DOUBLE,
 "slRestockGL" INTEGER,
 "slBOMDedComp" LOGICAL,
 "slSalesReturnQty" DOUBLE,
 "slPurchaseReturnGL" INTEGER,
 "slSpare1" CHAR(214),
 "slSpare2" CHAR(53),
 "slSpare3" CHAR(255),
 "slSpare4" CHAR(255),
 "slSpare5" CHAR(24) );SET TRUENULLCREATE = ON;
-- End Multi-Line Statement
CREATE INDEX "slLocStkIdx" USING 1  ON "StockLocation" ( "slIdxRecSub", "slIdxLocStock" );
CREATE INDEX "slStkLocIdx" USING 0  ON "StockLocation" ( "slIdxRecSub", "slIdxStockLoc" );
CREATE INDEX "slSuppIdx" USING 2  ON "StockLocation" ( "slIdxRecSub", "slIdxSupp" );
SET LEGACYTYPESALLOWED = OFF;
-- End Tables
