-- Database: EXCHCORECPA400 Metadata version: 1 Exported: 19-Feb-2025
-- Begin Tables
SET LEGACYTYPESALLOWED = ON;
-- Begin Multi-Line Statement
SET TRUENULLCREATE = OFF;CREATE TABLE "TransactionLines" USING 'Trans\Details.DAt' DCOMPRESS PAGESIZE=2048 LINKDUP=9 (
 "idxFolio" INTEGER,
 "tlFolio" INTEGER /* Column TransactionLines.tlFolio has the same offset as another column that is not type BIT */,
 "tlLinePos" INTEGER,
 "tlRunNo" INTEGER,
 "tlGLCode" INTEGER,
 "tlIdxGLNom" CHAR(5) /* Column TransactionLines.tlIdxGLNom has the same offset as another column that is not type BIT */,
 "tlIdxNomPeriod" CHAR(4),
 "tlShowInGL" LOGICAL /* Column TransactionLines.tlShowInGL has the same offset as another column that is not type BIT */,
 "tlCurrency" UTINYINT,
 "tlIdxCcyYrPr" CHAR(3) /* Column TransactionLines.tlIdxCcyYrPr has the same offset as another column that is not type BIT */,
 "tlYear" UTINYINT,
 "tlPeriod" UTINYINT,
 "tlDepartment" CHAR(3),
 "tlCostCentre" CHAR(3),
 "tlStockCode" LSTRING(21),
 "IdxStockCode" CHAR(16),
 "tlIdxStockCode" CHAR(20) /* Column TransactionLines.tlIdxStockCode has the same offset as another column that is not type BIT */,
 "idxLineNo" INTEGER,
 "tlLineNo" INTEGER /* Column TransactionLines.tlLineNo has the same offset as another column that is not type BIT */,
 "tlLineClass" CHAR(1),
 "tlDocType" UTINYINT,
 "tlQty_1" SMALLINT,
 "tlQty_2" INTEGER,
 "tlQtyMul_1" SMALLINT,
 "tlQtyMul_2" INTEGER,
 "tlNetVal_1" SMALLINT,
 "tlNetVal_2" INTEGER,
 "tlDiscount_1" SMALLINT,
 "tlDiscount_2" INTEGER,
 "tlVATCode" CHAR(1),
 "tlVATAmt_1" SMALLINT,
 "tlVATAmt_2" INTEGER,
 "tlPayStatus" CHAR(1),
 "tlPrevGLBal_1" SMALLINT,
 "tlPrevGLBal_2" INTEGER,
 "tlRecStatus" UTINYINT,
 "tlDiscFlag" CHAR(1),
 "tlQtyWOff_1" SMALLINT,
 "tlQtyWOff_2" INTEGER,
 "tlQtyDel_1" SMALLINT,
 "tlQtyDel_2" INTEGER,
 "tlCost_1" SMALLINT,
 "tlCost_2" INTEGER,
 "tlAcCode" LSTRING(11),
 "idxAcCode" CHAR(6),
 "tlIdxAcCode" CHAR(10) /* Column TransactionLines.tlIdxAcCode has the same offset as another column that is not type BIT */,
 "tlTransDate" CHAR(8),
 "tlIdxTransDate" CHAR(8) /* Column TransactionLines.tlIdxTransDate has the same offset as another column that is not type BIT */,
 "tlItemNo" LSTRING(4),
 "tlDescr" LSTRING(61),
 "tlJobCode" CHAR(10),
 "tlJobAnal" CHAR(10),
 "tlCompanyRate_1" SMALLINT,
 "tlCompanyRate_2" INTEGER,
 "tlDailyRate_1" SMALLINT,
 "tlDailyRate_2" INTEGER,
 "tlUnitWeight_1" SMALLINT,
 "tlUnitWeight_2" INTEGER,
 "tlStockDeductQty_1" SMALLINT,
 "tlStockDeductQty_2" INTEGER,
 "tlBOMKitLink" INTEGER,
 "tlOrderFolio" INTEGER,
 "tlOrderLineNo" INTEGER,
 "tlLocation" LSTRING(4),
 "IdxLocCode" CHAR(3),
 "tlQtyPicked_1" SMALLINT,
 "tlQtyPicked_2" INTEGER,
 "tlQtyPickedWO_1" SMALLINT,
 "tlQtyPickedWO_2" INTEGER,
 "tlUseQtyMul" LOGICAL,
 "tlNoSerialNos_1" SMALLINT,
 "tlNoSerialNos_2" INTEGER,
 "tlCOSGL" INTEGER,
 "tlOurRef" CHAR(10),
 "tlLineType" UTINYINT,
 "tlPriceByPack" LOGICAL,
 "tlQtyInPack" DOUBLE,
 "tlClearDate" CHAR(8),
 "tlUser1" LSTRING(31),
 "tlUser2" LSTRING(31),
 "tlUser3" LSTRING(31),
 "tlUser4" LSTRING(31),
 "tlB2BLinkFolio" INTEGER,
 "tlB2BLineNo" INTEGER,
 "tlUseLine" LOGICAL,
 "tlCOSConvRate" DOUBLE,
 "tlIncNetValue" DOUBLE,
 "tlAutoLineType" UTINYINT,
 "tlCISRateCode" CHAR(1),
 "tlCISRate" DOUBLE,
 "tlCostApport" DOUBLE,
 "tlNOMIOFlg" UTINYINT,
 "tlBinQty" DOUBLE,
 "tlCISAdjustment" DOUBLE,
 "tlDeductType" UTINYINT,
 "tlSerialReturnQty" DOUBLE,
 "tlBinReturnQty" DOUBLE,
 "tlDiscount2_1" SMALLINT,
 "tlDiscount2_2" INTEGER,
 "tlDiscount2Chr" CHAR(1),
 "tlDiscount3_1" SMALLINT,
 "tlDiscount3_2" INTEGER,
 "tlDiscount3Chr" CHAR(1),
 "tlDiscount3Type" UTINYINT,
 "tlECService" LOGICAL,
 "tlServiceStartDate" LSTRING(9),
 "tlIdxServiceStartDat" CHAR(8),
 "tlServiceEndDate" LSTRING(9),
 "tlECSalesTaxReported" DOUBLE,
 "tlPurchaseServiceTax" DOUBLE,
 "tlReference" LSTRING(21),
 "tlReceiptNo" LSTRING(21),
 "tlFromPostCode" LSTRING(16),
 "tlToPostCode" LSTRING(16),
 "tlUser5" LSTRING(31),
 "tlUser6" LSTRING(31),
 "tlUser7" LSTRING(31),
 "tlUser8" LSTRING(31),
 "tlUser9" LSTRING(31),
 "tlUser10" LSTRING(31),
 "tlThresholdCode" LSTRING(13),
 "tlMaterialsOnlyReten" LOGICAL,
 "tlIntrastatNoTC" LSTRING(3),
 "Spare2" CHAR(156) );SET TRUENULLCREATE = ON;
-- End Multi-Line Statement
CREATE INDEX "tlAcCodeIdx" USING 10  ON "TransactionLines" ( "tlIdxAcCode", "tlOurRef" );
CREATE INDEX "tlAnalIdx" USING 4  ON "TransactionLines" ( "tlLineClass", "tlIdxStockCode", "tlIdxTransDate" );
CREATE INDEX "tlCustAnalIdx" USING 6  ON "TransactionLines" ( "tlLineClass", "tlIdxAcCode", "tlIdxStockCode", "tlIdxTransDate" );
CREATE INDEX "tlFolioIdx" USING 0  ON "TransactionLines" ( "idxFolio", "tlLinePos" );
CREATE INDEX "tlIStockLedgerIdx" USING 8  ON "TransactionLines" ( "tlIdxStockCode", "tlIdxTransDate", "idxFolio" );
CREATE INDEX "tlLinkIdx" USING 5  ON "TransactionLines" ( "idxFolio", "idxLineNo" );
CREATE INDEX "tlNomIdx" USING 2  ON "TransactionLines" ( "tlGLCode", "tlIdxNomPeriod", "tlRunNo" );
CREATE INDEX "tlOurRefIdx" USING 11  ON "TransactionLines" ( "tlOurRef" );
CREATE INDEX "tlPostedIdx" USING 1  ON "TransactionLines" ( "tlRunNo", "tlGLCode" );
CREATE INDEX "tlReconIdx" USING 7  ON "TransactionLines" ( "tlIdxGLNom", "tlRecStatus", "tlIdxCcyYrPr" );
CREATE INDEX "tlServiceIdx" USING 9  ON "TransactionLines" ( "tlIdxAcCode", "tlECService", "tlIdxServiceStartDat" );
CREATE INDEX "tlStockIdx" USING 3  ON "TransactionLines" ( "tlIdxStockCode" );
CREATE INDEX "tlYearPeriodIdx" USING 12  ON "TransactionLines" ( "tlYear", "tlPeriod", "tlOurRef" );
SET LEGACYTYPESALLOWED = OFF;
-- End Tables
