-- Database: EXCHCORECPA400 Metadata version: 1 Exported: 19-Feb-2025
-- Begin Tables
SET LEGACYTYPESALLOWED = ON;
-- Begin Multi-Line Statement
SET TRUENULLCREATE = OFF;CREATE TABLE "Transactions" USING 'trans\document.dat' DCOMPRESS PAGESIZE=4096 LINKDUP=11 (
 "thRunNo" INTEGER,
 "thAcCode" LSTRING(11),
 "idxAcCode" CHAR(6),
 "thAutoNom" LOGICAL,
 "thOurRef" LSTRING(11),
 "idxOurRef" CHAR(10),
 "thIdxDocCode" CHAR(1) /* Column Transactions.thIdxDocCode has the same offset as another column that is not type BIT */,
 "thFolio" INTEGER,
 "idxFolio" INTEGER /* Column Transactions.idxFolio has the same offset as another column that is not type BIT */,
 "thCurrency" UTINYINT,
 "thIdxYearPeriod" CHAR(2),
 "thYear" UTINYINT /* Column Transactions.thYear has the same offset as another column that is not type BIT */,
 "thPeriod" UTINYINT,
 "thDueDate" LSTRING(9),
 "thIdxDueDate" CHAR(8),
 "thVATDate" LSTRING(9),
 "thIdxVATDate" CHAR(8),
 "thTransDate" LSTRING(9),
 "thIdxTransDate" CHAR(8),
 "idxAcType" CHAR(1),
 "thCustSupp" CHAR(1) /* Column Transactions.thCustSupp has the same offset as another column that is not type BIT */,
 "thCompanyRate_1" SMALLINT,
 "thCompanyRate_2" INTEGER,
 "thDailyRate_1" SMALLINT,
 "thDailyRate_2" INTEGER,
 "thIdxOLDYourRef" CHAR(10),
 "thOLDYourRef" CHAR(10) /* Column Transactions.thOLDYourRef has the same offset as another column that is not type BIT */,
 "thIdxBatchLink" CHAR(12),
 "thBatchLink" CHAR(12) /* Column Transactions.thBatchLink has the same offset as another column that is not type BIT */,
 "thAllocStat" CHAR(1),
 "thDocType" UTINYINT,
 "thVAT_Standard_1" SMALLINT,
 "thVAT_Standard_2" INTEGER,
 "thVAT_Exempt_1" SMALLINT,
 "thVAT_Exempt_2" INTEGER,
 "thVAT_Zero_1" SMALLINT,
 "thVAT_Zero_2" INTEGER,
 "thVAT_Rate1_1" SMALLINT,
 "thVAT_Rate1_2" INTEGER,
 "thVAT_Rate2_1" SMALLINT,
 "thVAT_Rate2_2" INTEGER,
 "thVAT_Rate3_1" SMALLINT,
 "thVAT_Rate3_2" INTEGER,
 "thVAT_Rate4_1" SMALLINT,
 "thVAT_Rate4_2" INTEGER,
 "thVAT_Rate5_1" SMALLINT,
 "thVAT_Rate5_2" INTEGER,
 "thVAT_Rate6_1" SMALLINT,
 "thVAT_Rate6_2" INTEGER,
 "thVAT_Rate7_1" SMALLINT,
 "thVAT_Rate7_2" INTEGER,
 "thVAT_Rate8_1" SMALLINT,
 "thVAT_Rate8_2" INTEGER,
 "thVAT_Rate9_1" SMALLINT,
 "thVAT_Rate9_2" INTEGER,
 "thVAT_RateT_1" SMALLINT,
 "thVAT_RateT_2" INTEGER,
 "thVAT_RateX_1" SMALLINT,
 "thVAT_RateX_2" INTEGER,
 "thVATRate_B_1" SMALLINT,
 "thVATRate_B_2" INTEGER,
 "thVATRate_C_1" SMALLINT,
 "thVATRate_C_2" INTEGER,
 "thVATRate_F_1" SMALLINT,
 "thVATRate_F_2" INTEGER,
 "thVATRate_G_1" SMALLINT,
 "thVATRate_G_2" INTEGER,
 "thVATRate_R_1" SMALLINT,
 "thVATRate_R_2" INTEGER,
 "thVATRate_W_1" SMALLINT,
 "thVATRate_W_2" INTEGER,
 "thVATRate_Y_1" SMALLINT,
 "thVATRate_Y_2" INTEGER,
 "thNetValue_1" SMALLINT,
 "thNetValue_2" INTEGER,
 "thTotalVAT_1" SMALLINT,
 "thTotalVAT_2" INTEGER,
 "thSettlePerc_1" SMALLINT,
 "thSettlePerc_2" INTEGER,
 "thTotSettleDisc_1" SMALLINT,
 "thTotSettleDisc_2" INTEGER,
 "thTotLineDisc_1" SMALLINT,
 "thTotLineDisc_2" INTEGER,
 "thDiscDays" SMALLINT,
 "thDiscTaken" LOGICAL,
 "thSettled_1" SMALLINT,
 "thSettled_2" INTEGER,
 "thAutoIncUnit" SMALLINT,
 "thAutoYear" UTINYINT,
 "thAutoPeriod" UTINYINT,
 "thSSDTransNat" UTINYINT,
 "thSSDTransMode" UTINYINT,
 "thRemitRef" LSTRING(11),
 "thAutoUnits" CHAR(1),
 "thHold" UTINYINT,
 "thTotalWeight_1" SMALLINT,
 "thTotalWeight_2" INTEGER,
 "thDelAddr1" LSTRING(31),
 "thDelAddr2" LSTRING(31),
 "thDelAddr3" LSTRING(31),
 "thDelAddr4" LSTRING(31),
 "thDelAddr5" LSTRING(31),
 "thCurrVar_1" SMALLINT,
 "thCurrVar_2" INTEGER,
 "thTotal1_1" SMALLINT,
 "thTotal1_2" INTEGER,
 "thTotal2_1" SMALLINT,
 "thTotal2_2" INTEGER,
 "thTotalCost_1" SMALLINT,
 "thTotalCost_2" INTEGER,
 "thTotalInvoiced_1" SMALLINT,
 "thTotalInvoiced_2" INTEGER,
 "thIdxYourRefLong" CHAR(20),
 "thYourRefLong" CHAR(20) /* Column Transactions.thYourRefLong has the same offset as another column that is not type BIT */,
 "thAutoUntil" LSTRING(9),
 "thNomVATIO" CHAR(1),
 "thExternal" LOGICAL,
 "thPrinted" LOGICAL,
 "thCurrVariance_1" SMALLINT,
 "thCurrVariance_2" INTEGER,
 "thAmtSettled_1" SMALLINT,
 "thAmtSettled_2" INTEGER,
 "thSettledVAT_1" SMALLINT,
 "thSettledVAT_2" INTEGER,
 "thVATClaimed_1" SMALLINT,
 "thVATClaimed_2" INTEGER,
 "thBatchPayGL" INTEGER,
 "thAutoPost" LOGICAL,
 "thManualVAT" LOGICAL,
 "thSSDDelTerms" LSTRING(4),
 "thOnPickRun" LOGICAL,
 "thUser" LSTRING(11),
 "thNoLabels" SMALLINT,
 "thTagged" UTINYINT,
 "thPickRunNo" INTEGER,
 "thOrderMatch" LOGICAL,
 "thDelivNote" LSTRING(11),
 "thVATCompRate_1" SMALLINT,
 "thVATCompRate_2" INTEGER,
 "thVATDailyRate_1" SMALLINT,
 "thVATDailyRate_2" INTEGER,
 "thOrigCompRate_1" SMALLINT,
 "thOrigCompRate_2" INTEGER,
 "thOrigDailyRate_1" SMALLINT,
 "thOrigDailyRate_2" INTEGER,
 "thPostDiscAmt" DOUBLE,
 "thPostDiscTaken" LOGICAL,
 "thDrCrGL" INTEGER,
 "thJobCode" LSTRING(11),
 "thJobAnal" LSTRING(11),
 "thOutstOrder_1" SMALLINT,
 "thOutstOrder_2" INTEGER,
 "thSpare2" CHAR(8),
 "thUser1" LSTRING(31),
 "thUser2" LSTRING(31),
 "thLineType1" DOUBLE,
 "thLineType2" DOUBLE,
 "thLineType3" DOUBLE,
 "thLineType4" DOUBLE,
 "thLineType5" DOUBLE,
 "thLineType6" DOUBLE,
 "thDebtChaseNo" UTINYINT,
 "thBatOwnSettl" DOUBLE,
 "thBatPaySettl" DOUBLE,
 "thBatUntagged" LOGICAL,
 "thUser3" LSTRING(31),
 "thUser4" LSTRING(31),
 "thProcess" CHAR(1),
 "thSource" UTINYINT,
 "thMainTriRate" DOUBLE,
 "thMainTriEuro" UTINYINT,
 "thMainTriInvert" LOGICAL,
 "thMainTriFloat" LOGICAL,
 "thMainTriSpare" CHAR(10),
 "thVATTriRate" DOUBLE,
 "thVATTriEuro" UTINYINT,
 "thVATTriInvert" LOGICAL,
 "thVATTriFloat" LOGICAL,
 "thVATTriSpare" CHAR(10),
 "thOrigTriRate" DOUBLE,
 "thOrigTriEuro" UTINYINT,
 "thOrigTriInvert" LOGICAL,
 "thOrigTriFloat" LOGICAL,
 "thOrigTriSpare" CHAR(10),
 "thPreEuroTriRate" DOUBLE,
 "thPreEuroTriEuro" UTINYINT,
 "thPreEuroTriInvert" LOGICAL,
 "thPreEuroTriFloat" LOGICAL,
 "thPreEuroTriSpare" CHAR(10),
 "thPostDate" LSTRING(9),
 "thPORPickSOR" LOGICAL,
 "thBatchDiscAmount" DOUBLE,
 "thPrePost" UTINYINT,
 "thAuthorisedAmount" DOUBLE,
 "thTimeChanged" LSTRING(7),
 "thTimeCreated" LSTRING(7),
 "thCISTaxDue" DOUBLE,
 "thCISTaxDeclared" DOUBLE,
 "thCISManualTax" LOGICAL,
 "thCISDate" LSTRING(9),
 "thTotalCostApport" DOUBLE,
 "thCISEmployee" LSTRING(11),
 "thCISTotalGross" DOUBLE,
 "thCISSource" UTINYINT,
 "thExported" LOGICAL,
 "thCISGrossExclude" DOUBLE,
 "thWeekMonth" SMALLINT,
 "thWorkflowState" INTEGER,
 "thOverrideLocation" LSTRING(4),
 "thSpare7" CHAR(54),
 "thYourRef" CHAR(20),
 "thIdxYourRef" CHAR(20) /* Column Transactions.thIdxYourRef has the same offset as another column that is not type BIT */,
 "thUser5" LSTRING(31),
 "thUser6" LSTRING(31),
 "thUser7" LSTRING(31),
 "thUser8" LSTRING(31),
 "thUser9" LSTRING(31),
 "thUser10" LSTRING(31),
 "thDeliveryPostCode" LSTRING(21),
 "thOriginator" LSTRING(37),
 "thCreationTime" LSTRING(7),
 "thCreationDate" LSTRING(9),
 "thOrdPayOrderRef" LSTRING(11),
 "thOrdPayElement" UTINYINT,
 "thOrdPayFlags" UTINYINT,
 "thCreditCardType" LSTRING(5),
 "thCreditCardNumber" LSTRING(5),
 "thCreditCardExpiry" LSTRING(5),
 "thCreditCardAuthNo" LSTRING(21),
 "thCreditCardRefNo" LSTRING(71),
 "thCustomData1" LSTRING(31),
 "thDeliveryCountry" LSTRING(3),
 "thPPDPercentage" DOUBLE,
 "thPPDDays" SMALLINT,
 "thPPDGoodsValue" DOUBLE,
 "thPPDVATValue" DOUBLE,
 "thPPDTaken" UTINYINT,
 "thPPDCreditNote" LOGICAL,
 "thBatchPayPPDStatus" UTINYINT,
 "thIntrastOutOfPeriod" LOGICAL,
 "thUser11" LSTRING(31),
 "thUser12" LSTRING(31),
 "thTaxRegion" INTEGER,
 "thAnonymised" LOGICAL,
 "thAnonymisedDate" LSTRING(9),
 "thAnonymisedTime" LSTRING(7),
 "thApplyReverseCharge" LOGICAL,
 "thSpare1" CHAR(255),
 "thSpare3" CHAR(17) );SET TRUENULLCREATE = ON;
-- End Multi-Line Statement
CREATE INDEX "thAccountIdx" USING 1  ON "Transactions" ( "idxAcCode", "idxAcType", "thAutoNom" );
CREATE INDEX "thAllocStatusIdx" USING 11  ON "Transactions" ( "thAllocStat" );
CREATE INDEX "thBatchLinkIdx" USING 7  ON "Transactions" ( "thIdxBatchLink" );
CREATE INDEX "thCustDueIdx" USING 4  ON "Transactions" ( "idxAcType", "idxAcCode", "thIdxDueDate", "thAutoNom" );
CREATE INDEX "thDateIdx" USING 9  ON "Transactions" ( "thIdxTransDate" );
CREATE UNIQUE INDEX "thFolioIdx" USING 3  ON "Transactions" ( "idxFolio" );
CREATE UNIQUE INDEX "thOurRefIdx" USING 2  ON "Transactions" ( "idxOurRef" );
CREATE INDEX "thPeriodIdx" USING 10  ON "Transactions" ( "thIdxYearPeriod" );
CREATE UNIQUE INDEX "thRunFolioIdx" USING 0  ON "Transactions" ( "thRunNo", "thIdxDocCode", "idxFolio" );
CREATE INDEX "thVATOurRefIdx" USING 5  ON "Transactions" ( "thIdxVATDate", "idxOurRef" );
CREATE INDEX "thYourRefIdx" USING 6  ON "Transactions" ( "thIdxYourRef" );
CREATE INDEX "YourRefLongIdx" USING 8  ON "Transactions" ( "thIdxYourRefLong" );
SET LEGACYTYPESALLOWED = OFF;
-- End Tables
